name: Build Sphinx Documentation

on:
  push:
    branches:
      - documentacion  # Ejecutar en la rama "documentacion"
  pull_request:
    branches:
      - documentacion

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      # 1. Chequear el repositorio
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Configurar Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 3. Instalar dependencias necesarias
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme

      # 4. Construir la documentación
      - name: Build Documentation
        run: |
          sphinx-build -b html source docs/build/html

      # 5. (Opcional) Publicar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
