name: Build Sphinx Documentation

on:
  push:
    branches:
      - main  # Cambia "main" al nombre de la rama en la que trabajas
  pull_request:
    branches:
      - main  # También se ejecutará en los pull requests a la rama "main"

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      # 1. Chequear el repositorio
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Configurar Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Cambia la versión según lo que necesites

      # 3. Instalar dependencias
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme  # Agrega otras extensiones si las usas

      # 4. Construir la documentación
      - name: Build Documentation
        run: |
          cd docs
          make html

      # 5. (Opcional) Publicar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html  # Ruta donde Sphinx genera la documentación
